# Generated by Django 2.1.7 on 2019-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Role',
            field=models.CharField(choices=[('TU', 'Tutor'), ('ST', 'Student')], default='ST', max_length=2),
        ),
    ]
