# Generated by Django 2.1.7 on 2019-03-30 22:29

from django.db import migrations, models
import leads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[leads.validators.validate_school_email]),
        ),
    ]
