# Generated by Django 2.1.7 on 2019-03-31 01:43

from django.db import migrations, models
import django.utils.timezone
import leads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190331_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[leads.validators.validate_school_email], verbose_name='email address'),
        ),
    ]
