# Generated by Django 2.1.7 on 2019-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190331_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.AlterField(
            model_name='lead',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
