# Generated by Django 2.1.7 on 2019-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190402_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availabilities',
            field=models.CharField(blank=True, default='blank', max_length=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tutor_rating',
            field=models.IntegerField(blank=True, default='5'),
        ),
    ]
