# Generated by Django 2.1.7 on 2019-04-17 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_appointment_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='tutor_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAppointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectAppointments', to='users.Subject'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TutorAppointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
