# Generated by Django 2.1.7 on 2019-04-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20190420_0143'),
        ('users', '0012_merge_20190420_0141'),
    ]

    operations = [
    ]
