# Generated by Django 2.2 on 2019-04-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(related_name='user_subjects', to='users.Subject'),
        ),
    ]
