# Generated by Django 2.1.7 on 2019-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, default='blank', max_length=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_rating',
            field=models.IntegerField(blank=True, default='5'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, default='blank', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='blank', max_length=40),
        ),
    ]
