# Generated by Django 2.1.7 on 2019-04-02 01:14

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190402_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='blank', max_length=254, unique=True, validators=[users.validators.validate_school_email]),
        ),
    ]
