# Generated by Django 2.1.7 on 2019-04-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190402_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(blank=True, default='5', primary_key=True, serialize=False)),
                ('tutor_id', models.IntegerField(blank=True, default='5')),
                ('client_id', models.IntegerField(blank=True, default='5')),
                ('course_id', models.IntegerField(blank=True, default='5')),
                ('additional_comments', models.CharField(blank=True, default='blank', max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('location', models.CharField(blank=True, default='blank', max_length=40)),
                ('status', models.CharField(blank=True, default='blank', max_length=20)),
                ('rating', models.IntegerField(blank=True, default='5')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(blank=True, default='5', primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, default='blank', max_length=40)),
                ('description', models.CharField(blank=True, default='blank', max_length=2000)),
            ],
        ),
    ]
