# Generated by Django 2.1.7 on 2019-04-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appointment_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='course_name',
        ),
    ]
