# Generated by Django 2.1.7 on 2019-04-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190420_0107'),
        ('users', '0011_auto_20190420_0109'),
    ]

    operations = [
    ]
