# Generated by Django 2.2 on 2019-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190422_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(related_name='user_subjects', to='users.Subject'),
        ),
    ]
