# Generated by Django 2.2 on 2019-04-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190422_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subjects',
        ),
    ]
