# Generated by Django 2.1.7 on 2019-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_appointment_availabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='blank', max_length=50),
        ),
    ]
