# Generated by Django 2.1.7 on 2019-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190429_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='report_card',
            field=models.CharField(blank=True, default='blank', max_length=2000),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='blank', max_length=40),
        ),
    ]
